[versions]
org-jacoco = "0.8.8"
org-jetbrains-kotlin = "1.7.10"
org-mockito = "5.2.0"
org-testcontainers = "1.17.6"

[libraries]
com-fasterxml-jackson-core-jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.1"
com-github-java-json-tools-json-patch = "com.github.java-json-tools:json-patch:1.13"
com-google-guava = "com.google.guava:guava:32.0.1-jre"
com-typesafe-config = "com.typesafe:config:1.4.2"
net-jodah-failsafe = "net.jodah:failsafe:2.4.4"
org-apache-commons-commons-collections4 = "org.apache.commons:commons-collections4:4.4"
org-apache-commons-commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.9.0"
org-apache-commons-commons-lang3 = "org.apache.commons:commons-lang3:3.12.0"
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.17.1"
org-jacoco-org-jacoco-agent = { module = "org.jacoco:org.jacoco.agent", version.ref = "org-jacoco" }
org-jacoco-org-jacoco-ant = { module = "org.jacoco:org.jacoco.ant", version.ref = "org-jacoco" }
org-jetbrains-annotations = "org.jetbrains:annotations:13.0"
org-jetbrains-kotlin-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "org-jetbrains-kotlin" }
org-junit-jupiter-junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.2"
org-mockito-mockito-core = { module = "org.mockito:mockito-core", version.ref = "org-mockito" }
org-mockito-mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "org-mockito" }
org-mockito-mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "org-mockito" }
org-mongodb-mongodb-driver-sync = "org.mongodb:mongodb-driver-sync:4.9.0"
org-postgresql = "org.postgresql:postgresql:42.5.4"
org-projectlombok-lombok = "org.projectlombok:lombok:1.18.26"
org-slf4j-slf4j-api = "org.slf4j:slf4j-api:1.7.36"
org-testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "org-testcontainers" }
org-testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "org-testcontainers" }

[plugins]
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.47.0"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.0"
org-hypertrace-ci-utils-plugin = "org.hypertrace.ci-utils-plugin:0.3.0"
org-hypertrace-code-style-plugin = "org.hypertrace.code-style-plugin:1.1.0"
org-hypertrace-integration-test-plugin = "org.hypertrace.integration-test-plugin:0.2.0"
org-hypertrace-jacoco-report-plugin = "org.hypertrace.jacoco-report-plugin:0.2.0"
org-hypertrace-publish-plugin = "org.hypertrace.publish-plugin:1.0.2"
org-hypertrace-repository-plugin = "org.hypertrace.repository-plugin:0.4.0"
org-owasp-dependencycheck = "org.owasp.dependencycheck:8.2.1"
